### ISSUE TITLE
TypeError: attributes() got an unexpected keyword argument 'apply_with_init'

### ISSUE THREAD

**Issue by cas--** [pyca/service_identity#13]
Debian/Ubuntu users have found that service_identity 14.0.0 is crashing Deluge.

    File "/usr/lib/python2.7/dist-packages/service_identity/pyopenssl.py", line 14, in <module>
        from ._common import (
    File "/usr/lib/python2.7/dist-packages/service_identity/_common.py", line 136, in <module>
        @attributes(["pattern"], apply_with_init=False)
    TypeError: attributes() got an unexpected keyword argument 'apply_with_init'

https://bugs.launchpad.net/ubuntu/+source/deluge/+bug/1492394
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=797921

It looks like it might be fixed in your repo as the code has changed dramatically for `_common`.

**Comment by hynek** [comment]
`apply_with_init` has been added to characteristic 14.0.0 which service_identity 14.0.0 depends on. I’m a bit surprised that you got it installed with mismatching dependencies?

**Comment by cas--** [comment]
Ah ok so it's a packaging issue then, I'll close this then :)

**Comment by mithrandi** [comment]
Yes, this is a bug in the Debian (and Ubuntu) packaging: the `python-characteristic` package doesn't ship the metadata that explains how to interpret the version number, and `python-service-identity` doesn't have an override for this metadata, so it doesn't have a versioned dependency on `python-characteristic`. Thus, since the new `python-characteristic` was only uploaded some time after the new `python-service-identity`, there was a window where you would get incompatible versions installed without the package manager preventing it.

**Comment by gitressa** [comment]
Can someone help me with upgrading python-characteristic to version 14.0.0?
I tried <code>sudo apt-get install python-characteristic=14.0.0</code> but get this result:
<pre>Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Version '14.0.0' for 'python-characteristic' was not found</pre>
